name: Build and Push DPO Telegram Bot
run-name: Bot Deployment triggered by ${{ github.actor }}

env:
  IMAGE_NAME: dpo_telegram_bot
  # if problem with docker: sudo chown $USER /var/run/docker.sock

on:
  workflow_dispatch:  # This makes the workflow manual
  push:

jobs:
  build:
    name: Build DPO TGBOT Image
    runs-on: [self-hosted]
    if: startsWith(github.event.head_commit.message, 'Deploy.')  # Deploy only if commit message starts with "Deploy. "
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image Locally
        run: |
          docker build --build-arg TG_TOKEN=${{ secrets.TG_BOT_TOKEN }} -t ${{ env.IMAGE_NAME }} -f ./Dockerfile .

  deploy:
    name: Deploy Docker Container
    runs-on: [self-hosted]
    needs: build
    if: startsWith(github.event.head_commit.message, 'Deploy. ')
    steps:
      - name: Stop and Remove Old Container
        run: |
          if [ "$(docker ps -a -q -f name=tg_bot_dpo)" ]; then
            docker stop tg_bot_dpo
            docker rm tg_bot_dpo
          fi

      - name: Create Docker Network
        run: |
          if [ -z "$(docker network ls -q -f name=tgnetwork)" ]; then
            docker network create tgnetwork
          fi

      - name: Run PostgreSQL Container
        run: |
          if [ -z "$(docker ps -a -q -f name=postgres_dpo)" ]; then
            docker run -d \
              --name postgres_dpo \
              --restart always \
              --network tgnetwork \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
              -p 5445:5432 \
              postgres:latest
          fi

      - name: Deploy Container
        run: |
          docker run -d \
            --name tg_bot_dpo \
            --restart always \
            --network tgnetwork \
            -e TG_TOKEN=${{ secrets.TG_BOT_TOKEN }} \
            -e DB_HOST=postgres_dpo \
            -e DB_PORT=5445
            -e DB_USER=${{ secrets.POSTGRES_USER }} \
            -e DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            -e DB_NAME=${{ secrets.POSTGRES_DB }} \
            ${{ env.IMAGE_NAME }}